CREATE DATABASE MEDICALCOMPANY
--DROP DATABASE MEDICALCOMPANY
GO
USE MEDICALCOMPANY
GO

CREATE TABLE PRODUCT(
	PRO_ID VARCHAR(10),
	PRO_NAME NVARCHAR(50),
	SALEPRICE DECIMAL(10,0),
	QUANTITY INT,
	PRIMARY KEY(PRO_ID)
)
GO

CREATE TABLE IMPORT(
	IMPORT_ID VARCHAR(10),
	PRO_ID VARCHAR(10) FOREIGN KEY REFERENCES PRODUCT(PRO_ID),
	PRODUCT_NAME NVARCHAR(50),
	IMPORT_DATE DATE,
	PRICE DECIMAL(10,0),
	QUANTITY INT

	PRIMARY KEY(IMPORT_ID)
)
GO

CREATE TABLE Temp_IMPORT(
	IMPORT_ID VARCHAR(10),
	PRO_ID VARCHAR(10) FOREIGN KEY REFERENCES PRODUCT(PRO_ID),
	PRODUCT_NAME NVARCHAR(50),
	IMPORT_DATE DATE,
	PRICE DECIMAL(10,0),
	QUANTITY INT

	PRIMARY KEY(IMPORT_ID)
)
GO
--DROP TABLE Temp_IMPORT

CREATE TABLE EXPORT(
	EXPORT_ID VARCHAR(10),
	PRO_ID VARCHAR(10) FOREIGN KEY REFERENCES PRODUCT(PRO_ID),
	PRODUCT_NAME NVARCHAR(50),
	EXPORT_DATE DATE,
	QUANTITY INT,
	PRICE DECIMAL(10,0),
	DELIVERY_STATUS NVARCHAR(30),
	PAYMENT_STATUS NVARCHAR(30),
	PRIMARY KEY(EXPORT_ID)
)
GO
--DROP TABLE EXPORT
CREATE TABLE Temp_EXPORT(
	EXPORT_ID VARCHAR(10),
	PRO_ID VARCHAR(10) FOREIGN KEY REFERENCES PRODUCT(PRO_ID),
	PRODUCT_NAME NVARCHAR(50),
	EXPORT_DATE DATE,
	QUANTITY INT,
	PRICE DECIMAL(10,0),
	DELIVERY_STATUS NVARCHAR(30),
	PAYMENT_STATUS NVARCHAR(30),
	PRIMARY KEY(EXPORT_ID)
)
GO

INSERT INTO PRODUCT VALUES ('P1', 'Dong Trung Ha Thao', '800000', 100)
INSERT INTO PRODUCT VALUES ('P2', 'Nuoc Hong Sam', '900000', 150)
INSERT INTO PRODUCT VALUES ('P3', 'Alipas', '500000', 50)
INSERT INTO PRODUCT VALUES ('P4', 'Vien Uong Sua Ong Chua', '550000', 75)
INSERT INTO PRODUCT VALUES ('P5', 'Nutra Vision', '300000', 40)
INSERT INTO PRODUCT VALUES ('P6', 'Suntory Sesamin Ex', '450000', 100)
INSERT INTO PRODUCT VALUES ('P7', 'Vitamin tong hop', '200000', 100)
GO

-- set date format
SET DATEFORMAT dmy
GO

--proc add import
CREATE PROC IMPORT_ORDER
	@IID VARCHAR(10),
	@Pro_id VARCHAR(10),
	@pro_name NVARCHAR(50),
	@IDATE DATE,
	@PRICE DECIMAL(10, 0),
	@QUANTITY INT
AS
BEGIN
	INSERT INTO IMPORT VALUES(@IID, @Pro_id, @pro_name, @IDATE, @PRICE, @QUANTITY)
	INSERT INTO Temp_IMPORT VALUES(@IID, @Pro_id, @pro_name, @IDATE, @PRICE, @QUANTITY)
END
GO
--DROP PROC IMPORT_ORDER
--EXEC IMPORT_ORDER @IID = 'I21', @Pro_id = 'P7', @pro_name = 'Vitamin tong hop', @IDATE = '20/01/2022', @PRICE = '400000', @QUANTITY = 50
--SELECT * FROM IMPORT

CREATE PROC UPDATE_IMPORT_ORDER
	@IID VARCHAR(10),
	@Pro_id VARCHAR(10),
	@pro_name NVARCHAR(50),
	@IDATE DATE,
	@PRICE DECIMAL(10, 0),
	@QUANTITY INT
AS
BEGIN
	UPDATE IMPORT SET IMPORT_ID = @IID, PRO_ID = @Pro_id, PRODUCT_NAME = @pro_name, IMPORT_DATE = @IDATE, PRICE = @PRICE, QUANTITY = @QUANTITY
	WHERE IMPORT_ID = @IID;
	UPDATE Temp_IMPORT SET IMPORT_ID = @IID, PRO_ID = @Pro_id, PRODUCT_NAME = @pro_name, IMPORT_DATE = @IDATE, PRICE = @PRICE, QUANTITY = @QUANTITY
	WHERE IMPORT_ID = @IID;
END
GO

--delete import information
CREATE PROC DELETE_IMPORT_ORDER
	@id varchar(10)
as
BEGIN
	DELETE FROM IMPORT WHERE IMPORT_ID = @id;
	DELETE FROM Temp_IMPORT WHERE IMPORT_ID = @id;
END
GO

--display import information
CREATE PROC showIMPORT
AS
BEGIN
	SELECT * FROM IMPORT
END
GO

--display temporary import table when input
CREATE PROC showTempIMPORT
AS
BEGIN
	SELECT * FROM Temp_IMPORT
END
GO

--delete temporary import table values
CREATE PROC delTempImportValue
as
begin
	DELETE FROM Temp_IMPORT
end
go
--select * from IMPORT
--delete from IMPORT where IMPORT_ID = 'I1'

-- proc add export
CREATE PROC EXPORT_ORDER
	@EID VARCHAR(10),
	@Pro_id VARCHAR(10),
	@pro_name NVARCHAR(50),
	@EDATE DATE,
	@QUANTITY INT,
	@PRICE DECIMAL(10, 0),
	@deliver_status nvarchar(30),
	@payment_status nvarchar(30)
AS
BEGIN
	INSERT INTO EXPORT VALUES(@EID, @Pro_id, @pro_name, @EDATE, @QUANTITY, @PRICE, @deliver_status, @payment_status);
	INSERT INTO Temp_EXPORT VALUES(@EID, @Pro_id, @pro_name, @EDATE, @QUANTITY, @PRICE, @deliver_status, @payment_status);
END
GO

CREATE PROC UPDATE_EXPORT_ORDER
	@EID VARCHAR(10),
	@Pro_id VARCHAR(10),
	@pro_name NVARCHAR(50),
	@EDATE DATE,
	@QUANTITY INT,
	@PRICE DECIMAL(10, 0),
	@deliver_status nvarchar(30),
	@payment_status nvarchar(30)
AS
BEGIN
	UPDATE EXPORT SET EXPORT_ID = @EID, PRO_ID = @Pro_id, PRODUCT_NAME = @pro_name, EXPORT_DATE = @EDATE, QUANTITY = @QUANTITY, 
	PRICE = @PRICE, DELIVERY_STATUS = @deliver_status, PAYMENT_STATUS = @payment_status
	WHERE EXPORT_ID = @EID;
	UPDATE Temp_EXPORT SET EXPORT_ID = @EID, PRO_ID = @Pro_id, PRODUCT_NAME = @pro_name, EXPORT_DATE = @EDATE, QUANTITY = @QUANTITY, 
	PRICE = @PRICE, DELIVERY_STATUS = @deliver_status, PAYMENT_STATUS = @payment_status
	WHERE EXPORT_ID = @EID;
END
GO

--delete export information
CREATE PROC DELETE_EXPORT_ORDER
	@id varchar(10)
as
BEGIN
	DELETE FROM EXPORT WHERE EXPORT_ID = @id;
	DELETE FROM Temp_EXPORT WHERE EXPORT_ID = @id;
END
GO

--display Export information
CREATE PROC showEXPORT
AS
BEGIN
	SELECT * FROM EXPORT
END
GO

--display temporary export table when input
CREATE PROC showTempEXPORT
AS
BEGIN
	SELECT * FROM Temp_EXPORT
END
GO

--delete temporary export values
CREATE PROC delTempExportValue
as
begin
	DELETE FROM Temp_EXPORT
end
go
--select * from EXPORT
--delete from EXPORT