CREATE DATABASE MEDICALCOMPANY
--DROP DATABASE MEDICALCOMPANY
GO
USE MEDICALCOMPANY
GO

CREATE TABLE SUPPLIER(
	SUP_ID VARCHAR(10),
	SUP_NAME NVARCHAR(50),
	PRIMARY KEY(SUP_ID)
)
GO

CREATE TABLE IMPORT(
	IMPORT_ID VARCHAR(10),
	SUP_ID VARCHAR(10) FOREIGN KEY REFERENCES SUPPLIER(SUP_ID),
	IMPORT_DATE DATE,
	PRICE DECIMAL(10,0),

	PRIMARY KEY(IMPORT_ID)
)
GO

CREATE TABLE PRODUCT(
	PRO_ID VARCHAR(10),
	PRO_NAME NVARCHAR(50),
	SALEPRICE DECIMAL(10,0),
	QUANTITY INT,
	PRIMARY KEY(PRO_ID)
)
GO

CREATE TABLE IMPORT_DETAIL(
	IMPORT_ID VARCHAR(10) FOREIGN KEY REFERENCES IMPORT(IMPORT_ID),
	PRO_ID VARCHAR(10) FOREIGN KEY REFERENCES PRODUCT(PRO_ID),
	SL INT,

	PRIMARY KEY(IMPORT_ID, PRO_ID)
)
GO

CREATE TABLE AGENT(
	AGENT_ID VARCHAR(10),
	AGENT_NAME NVARCHAR(50),
	PRIMARY KEY(AGENT_ID)
)
GO

CREATE TABLE EXPORT(
	EXPORT_ID VARCHAR(10),
	PRO_ID VARCHAR(10) FOREIGN KEY REFERENCES PRODUCT(PRO_ID),
	PRO_NAME NVARCHAR(50),
	AGENT_ID VARCHAR(10) FOREIGN KEY REFERENCES AGENT(AGENT_ID),
	EXPORT_DATE DATE,
	QUANTITY INT,
	PRICE DECIMAL(10,0),
	ORDER_STATUS NVARCHAR(30),
	PAYMENT_STATUS NVARCHAR(30),
	PRIMARY KEY(EXPORT_ID)
)
GO

INSERT INTO SUPPLIER VALUES ('SUPP1', 'Duoc Tuong Lai'),
							('SUPP2', 'New Medicine'),
							('SUPP3', 'ABC')
GO

INSERT INTO PRODUCT VALUES ('P1', 'Dong Trung Ha Thao', '800000', 100)
INSERT INTO PRODUCT VALUES ('P2', 'Nuoc Hong Sam', '900000', 150)
INSERT INTO PRODUCT VALUES ('P3', 'Alipas', '500000', 50)
INSERT INTO PRODUCT VALUES ('P4', 'Vien Uong Sua Ong Chua', '550000', 75)
INSERT INTO PRODUCT VALUES ('P5', 'Nutra Vision', '300000', 40)
INSERT INTO PRODUCT VALUES ('P6', 'Suntory Sesamin Ex', '450000', 100)
INSERT INTO PRODUCT VALUES ('P7', 'Vitamin tong hop', '200000', 100)
GO

INSERT INTO AGENT VALUES ('A1', 'HEALTHCARE Corp.')
GO

SET DATEFORMAT dmy
GO
INSERT INTO EXPORT VALUES ('EX1','P1','Dong Trung Ha Thao', 'A1', '30/12/2021', 50, '50000000', 'DELILVERED', 'COMPLETED')
INSERT INTO EXPORT VALUES ('EX2','P2','Nuoc Hong Sam', 'A1', '20/12/2021', 40, '50000000', 'DELILVERED', 'COMPLETED')
GO

--FUNCTION
--income per month
CREATE FUNCTION INCOME(@NGAY INT)
RETURNS DECIMAL(10, 0)
AS
BEGIN
	DECLARE @TOTAL DECIMAL(10, 0)
	SET @TOTAL = (SELECT SUM(PRICE) FROM EXPORT WHERE MONTH(EXPORT_DATE) = @NGAY)
	RETURN @TOTAL
END
GO
--drop function dbo.INCOME
declare @date1 int
set @date1 = MONTH('31/12/2021')
select dbo.INCOME(@date1)
GO

--LẤY THÔNG TIN SẢN PHẨM BẰNG MÃ SẢN PHẨM
CREATE PROC GET_PRODUCT_BY_ID
	@proid varchar(10)
AS
BEGIN
	SELECT * FROM PRODUCT WHERE PRO_ID = @proid
END
GO
--exec GET_PRODUCT_BY_ID @proid = 'P7'
--go
--Drop procedure GET_PRODUCT_BY_ID


-- Lấy danh sách sản phẩm bán
CREATE PROC GET_PRODUCT_FOR_SALE
AS
BEGIN
	SELECT * FROM PRODUCT WHERE QUANTITY > 0
END
GO
--EXEC GET_PRODUCT_FOR_SALE

-- PROC GET ALL EXPORT INVOICE
CREATE PROC GET_INVOICE_ALL
AS
BEGIN
	SELECT * FROM EXPORT
END
GO
--EXEC GET_INVOICE_ALL

--proc get invoice based on id
CREATE PROC GET_INVOICE_DETAIL_BY_ID
	@exportid varchar(10)
AS
BEGIN 
	SELECT * FROM EXPORT
		WHERE EXPORT_ID = @exportid
END
GO
--EXEC GET_INVOICE_DETAIL_BY_ID @exportid = 'EX1'
--drop proc GET_INVOICE_DETAIL_BY_ID


--PROC THEM SAN PHAM
CREATE PROC IMPORT_PRODUCT
	@ID VARCHAR(10),
	@TENSP NVARCHAR(50),
	@GIABAN DECIMAL(10, 0),
	@QUANTITY INT
AS
BEGIN
	INSERT INTO PRODUCT VALUES (@ID, @TENSP, @GIABAN, @QUANTITY)
END
GO
--Exec IMPORT_PRODUCT @ID = 'P8', @TENSP = 'HAHA', @GIABAN = '500000', @QUANTITY = 10

--PROC THEM DON NHAP HANG
CREATE PROC IMPORT_ORDER
	@IID VARCHAR(10),
	@SUP_ID VARCHAR(10),
	@IDATE DATE,
	@PRICE DECIMAL(10, 0)
AS
BEGIN
	INSERT INTO IMPORT VALUES(@IID, @SUP_ID, @IDATE, @PRICE)
END
GO
--EXEC IMPORT_ORDER @IID = 'I21', @SUP_ID = 'SUPP3', @IDATE = '20/01/2022', @PRICE = '400000'
SELECT * FROM IMPORT
GO

--PROC THEM CHI TIET NHAP HANG
CREATE PROC ADD_IMPORT_DETAIL
	@PID VARCHAR(10),
	@QUANTITY INT
AS
BEGIN
	DECLARE @IID VARCHAR(10)
	SET @IID = (SELECT TOP(1) IMPORT_ID FROM IMPORT ORDER BY IMPORT_ID DESC)
	INSERT INTO IMPORT_DETAIL VALUES(@IID, @PID, @QUANTITY)
	UPDATE PRODUCT SET QUANTITY = QUANTITY + @QUANTITY WHERE PRO_ID = @PID
END
GO
--EXEC ADD_IMPORT_DETAIL @PID = 'P6', @QUANTITY = 20
--SELECT * FROM IMPORT_DETAIL
--SELECT * FROM PRODUCT
--DELETE FROM IMPORT_DETAIL WHERE PRO_ID = 'P6'
--DROP PROC ADD_IMPORT_DETAIL

--PROC THEM HOA DON BAN HANG
CREATE PROC EXPORT_ORDER
	@EID VARCHAR(10),
	@PID VARCHAR(10),
	@PNAME NVARCHAR(50),
	@AID VARCHAR(10),
	@DATE DATE,
	@QUANTITY INT,
	@PRICE DECIMAL(10, 0),
	@ORSTATUS NVARCHAR(30),
	@PSTATUS NVARCHAR(30)
AS
BEGIN
	INSERT INTO EXPORT VALUES(@EID, @PID, @PNAME, @AID, @DATE, @QUANTITY, @PRICE, @ORSTATUS, @PSTATUS)
END
GO
EXEC EXPORT_ORDER @EID = 'EX3', @PID = 'P5', @PNAME = 'Nutra Vision', @AID = 'A1', @DATE = '31/12/2021', @QUANTITY = 30, @PRICE = '10000000', 
	@ORSTATUS = 'DELIVERING', @PSTATUS = 'COMPLETED'
SELECT * FROM EXPORT
GO
--PROC DANH SACH DON NHAP
CREATE PROC IMPORT_LIST
AS
BEGIN
	SELECT * FROM IMPORT
END
GO

--PROC DANH SACH CHI TIET DON NHAP
CREATE PROC DS_CTDN
	@IID INT
AS
BEGIN
	SELECT A.IMPORT_ID, A.PRO_ID, B.PRO_NAME, A.SL FROM IMPORT_DETAIL AS A, PRODUCT AS B WHERE IMPORT_ID = @IID AND A.PRO_ID = B.PRO_ID
END
GO