//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accountant
    {
        public string ACCOUNTANT_ID { get; set; }
        public string ACCOUNTANT_NAME { get; set; }
        public string GENDER { get; set; }
        public string SDT { get; set; }
    }
}
